// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1A1cpMIiolhbTSe5AXZhSkDz8p2-c1uw',
    appId: '1:1038567689751:web:07534baa712b8181379652',
    messagingSenderId: '1038567689751',
    projectId: 'insectpedia-1f996',
    authDomain: 'insectpedia-1f996.firebaseapp.com',
    storageBucket: 'insectpedia-1f996.firebasestorage.app',
    measurementId: 'G-XPLFX2QCLB',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-53wuqucKTENeSD3rbrKDFV6IXJ_qupk',
    appId: '1:1038567689751:ios:6b8854b0292c4ee4379652',
    messagingSenderId: '1038567689751',
    projectId: 'insectpedia-1f996',
    storageBucket: 'insectpedia-1f996.firebasestorage.app',
    iosBundleId: 'com.example.insectpedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-53wuqucKTENeSD3rbrKDFV6IXJ_qupk',
    appId: '1:1038567689751:ios:6b8854b0292c4ee4379652',
    messagingSenderId: '1038567689751',
    projectId: 'insectpedia-1f996',
    storageBucket: 'insectpedia-1f996.firebasestorage.app',
    iosBundleId: 'com.example.insectpedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1A1cpMIiolhbTSe5AXZhSkDz8p2-c1uw',
    appId: '1:1038567689751:web:292c0db46f6789c3379652',
    messagingSenderId: '1038567689751',
    projectId: 'insectpedia-1f996',
    authDomain: 'insectpedia-1f996.firebaseapp.com',
    storageBucket: 'insectpedia-1f996.firebasestorage.app',
    measurementId: 'G-M4SSNXTNZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR5jvaEwuhLiWCPeTQySoIyM9UAKL-qIw',
    appId: '1:1038567689751:android:8af1ea0e97fe422b379652',
    messagingSenderId: '1038567689751',
    projectId: 'insectpedia-1f996',
    storageBucket: 'insectpedia-1f996.firebasestorage.app',
  );

}